name: refresh datasus files metadata

on:
  schedule:
    - cron: "1 3 * * *"    #runs at 03:01 UTC everyday

jobs:
  getdataandrefreshmap:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 #install the python needed
          cache: 'pip' # cache the pip dependencies
      - name: Install dependencies
        run: |
          if [ -f pyproject.toml ]; then pip install .; fi
      - name: execute py script
        run: |
          python update-metadata.py

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add metadata/
          git commit -m "Automated update of datasus files metadata" -a

      - name: Push
        if: steps.verify_diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
